---
title: "**Gráfico de Pastel: Cámara de Diputados México (2021-2024)**"
author: "Alfredo Aro Terleira"
output: html_document
---

## Importamos la base de datos

```{r}
library(rio)
d_2021 = import("diputados_2021.xlsx")
```

# Gráfico 1: Porcentaje de mujeres y hombres en toda la Cámara de Diputados

## Paso 1.1: Codificamos

```{r}
library(ggplot2)
library(dplyr)
```

```{r}
# Calculamos el total de mujeres y hombres
total_mujeres = sum(d_2021$MUJERES)
total_hombres = sum(d_2021$HOMBRES)

# Creamos un dataframe para el gráfico
sexo_total = data.frame(
  Sexo = c("Mujeres","Hombres"),
  Total = c(total_mujeres, total_hombres)
)

# Calculamos el porcentaje
sexo_total$Porcentaje = round(sexo_total$Total / sum(sexo_total$Total) * 100, 1)

# Gráfico de pastel
ggplot(sexo_total, aes(x = "", y = Total, fill = Sexo)) +
  geom_bar(stat = "identity", width = 1) +
  coord_polar(theta = "y") +
  theme_void() +
  labs(title = "Distribución de Mujeres y Hombres \nen la Cámara de Diputados (2021-2024)") +
  theme(
    legend.title = element_blank(),
    plot.title = element_text(hjust = 0.2, size = 20, face = "bold") 
  ) +
  scale_fill_manual(values = c("Mujeres" = "#FF69B4", "Hombres" = "#1E88E5")) +
  geom_text(aes(label = paste(Porcentaje, "%")), position = position_stack(vjust = 0.5))
```
```{r}
# Guardamos el gráfico
ggsave("grafico_2021_hym.png", width = 8, height = 6)
```

# Gráfico 2: Porcentaje de mujeres y hombres por partido

## Paso 2.1: Codificamos

```{r}
library(ggplot2)
library(dplyr)
library(tidyr)
```

```{r}
# Creamos un dataframe para mujeres y hombres por partido
sexo_partido = d_2021 %>%
  select(PARTIDO, MUJERES, HOMBRES) %>%
  gather(key = "Sexo", value = "Total", MUJERES, HOMBRES) %>%
  group_by(PARTIDO) %>%
  mutate(Porcentaje = Total / sum(Total) * 100) # Normalizamos a porcentajes

# Gráfico de pastel por partido
ggplot(sexo_partido, aes(x = "", y = Porcentaje, fill = Sexo)) +
  geom_bar(stat = "identity", width = 1) +
  coord_polar(theta = "y") +
  facet_wrap(~PARTIDO, ncol = 4) + # Distribuir gráficos por partido
  theme_void() +
  labs(title = "Distribución de Mujeres y Hombres por Partido (2021-2024)") +
  theme(
    legend.title = element_blank(),
    strip.text = element_text(size = 9, face = "bold"),
    plot.title = element_text(hjust = 0.3, size = 14, face = "bold") # Centrar el título
  ) +
  scale_fill_manual(values = c("MUJERES" = "#FF69B4", "HOMBRES" = "#1E88E5")) +
  geom_text(aes(label = paste0(round(Porcentaje, 1), "%")), 
            position = position_stack(vjust = 0.5), size = 3)
```

```{r}
# Guardamos la imagen
ggsave("2021_hym_partidos.png", width = 8, height = 6)
```

